-- Sostituisce le 4 squadre fittizie del seed originale (V2) con le 20 squadre
-- reali della Serie A e rose complete (25 giocatori ciascuna: 3 P / 8 D / 8 C / 6 A),
-- con prezzi e "strength" pensati per rispecchiare in modo realistico i valori
-- di mercato/qualita' relativa tra le squadre (stile quotazioni fantacalcio).
--
-- Nota: i nomi dei giocatori sono basati sulle rose reali della Serie A cosi'
-- come note al momento della scrittura di questa migration; non sono garantiti
-- sincronizzati con trasferimenti/infortuni successivi. Servono a fornire dati
-- di partenza realistici per il motore di simulazione, non un feed live.
--
-- Essendo un reset completo della "stagione demo", azzeriamo anche calendario e
-- statistiche esistenti: al prossimo avvio FixtureGenerationService rigenera il
-- calendario (guardia basata su matchday vuota) con le nuove 20 squadre.

DELETE FROM player_match_stats;
DELETE FROM match;
DELETE FROM matchday;
DELETE FROM player;
DELETE FROM team;

INSERT INTO team (name, strength) VALUES
    ('Napoli', 88),
    ('Inter', 87),
    ('Juventus', 82),
    ('Milan', 80),
    ('Atalanta', 79),
    ('Roma', 76),
    ('Bologna', 75),
    ('Lazio', 74),
    ('Fiorentina', 73),
    ('Como', 66),
    ('Torino', 62),
    ('Udinese', 60),
    ('Genoa', 58),
    ('Cagliari', 56),
    ('Hellas Verona', 54),
    ('Lecce', 52),
    ('Parma', 51),
    ('Sassuolo', 50),
    ('Pisa', 46),
    ('Cremonese', 45);

-- Napoli (strength 88, fascia elite) — 3 P / 8 D / 8 C / 6 A
INSERT INTO player (first_name, last_name, team_id, shirt_number, "position", price, injured) VALUES
    ('Alex', 'Meret', (SELECT id FROM team WHERE name = 'Napoli'), 1, 'P', 22, FALSE),
    ('Elia', 'Caprile', (SELECT id FROM team WHERE name = 'Napoli'), 12, 'P', 11, FALSE),
    ('Nikita', 'Contini', (SELECT id FROM team WHERE name = 'Napoli'), 22, 'P', 6, FALSE),
    ('Giovanni', 'Di Lorenzo', (SELECT id FROM team WHERE name = 'Napoli'), 2, 'D', 20, FALSE),
    ('Alessandro', 'Buongiorno', (SELECT id FROM team WHERE name = 'Napoli'), 3, 'D', 17, FALSE),
    ('Amir', 'Rrahmani', (SELECT id FROM team WHERE name = 'Napoli'), 4, 'D', 15, FALSE),
    ('Sam', 'Beukema', (SELECT id FROM team WHERE name = 'Napoli'), 5, 'D', 13, FALSE),
    ('Mathias', 'Olivera', (SELECT id FROM team WHERE name = 'Napoli'), 6, 'D', 11, FALSE),
    ('Leonardo', 'Spinazzola', (SELECT id FROM team WHERE name = 'Napoli'), 13, 'D', 9, FALSE),
    ('Juan', 'Jesus', (SELECT id FROM team WHERE name = 'Napoli'), 14, 'D', 7, TRUE),
    ('Luca', 'Marianucci', (SELECT id FROM team WHERE name = 'Napoli'), 15, 'D', 5, FALSE),
    ('Kevin', 'De Bruyne', (SELECT id FROM team WHERE name = 'Napoli'), 7, 'C', 50, FALSE),
    ('Stanislav', 'Lobotka', (SELECT id FROM team WHERE name = 'Napoli'), 8, 'C', 43, FALSE),
    ('Frank', 'Anguissa', (SELECT id FROM team WHERE name = 'Napoli'), 10, 'C', 38, FALSE),
    ('Scott', 'McTominay', (SELECT id FROM team WHERE name = 'Napoli'), 16, 'C', 33, FALSE),
    ('Billy', 'Gilmour', (SELECT id FROM team WHERE name = 'Napoli'), 17, 'C', 28, FALSE),
    ('Eljif', 'Elmas', (SELECT id FROM team WHERE name = 'Napoli'), 18, 'C', 23, FALSE),
    ('Michael', 'Folorunsho', (SELECT id FROM team WHERE name = 'Napoli'), 20, 'C', 18, FALSE),
    ('Gianluca', 'Gaetano', (SELECT id FROM team WHERE name = 'Napoli'), 21, 'C', 13, FALSE),
    ('Romelu', 'Lukaku', (SELECT id FROM team WHERE name = 'Napoli'), 9, 'A', 60, FALSE),
    ('Lorenzo', 'Lucca', (SELECT id FROM team WHERE name = 'Napoli'), 11, 'A', 48, FALSE),
    ('David', 'Neres', (SELECT id FROM team WHERE name = 'Napoli'), 19, 'A', 39, FALSE),
    ('Matteo', 'Politano', (SELECT id FROM team WHERE name = 'Napoli'), 23, 'A', 30, FALSE),
    ('Noa', 'Lang', (SELECT id FROM team WHERE name = 'Napoli'), 24, 'A', 21, FALSE),
    ('Giacomo', 'Raspadori', (SELECT id FROM team WHERE name = 'Napoli'), 25, 'A', 15, FALSE);

-- Inter (strength 87, fascia elite) — 3 P / 8 D / 8 C / 6 A
INSERT INTO player (first_name, last_name, team_id, shirt_number, "position", price, injured) VALUES
    ('Yann', 'Sommer', (SELECT id FROM team WHERE name = 'Inter'), 1, 'P', 22, FALSE),
    ('Josep', 'Martinez', (SELECT id FROM team WHERE name = 'Inter'), 12, 'P', 11, FALSE),
    ('Raffaele', 'Di Gennaro', (SELECT id FROM team WHERE name = 'Inter'), 22, 'P', 6, FALSE),
    ('Alessandro', 'Bastoni', (SELECT id FROM team WHERE name = 'Inter'), 2, 'D', 20, FALSE),
    ('Francesco', 'Acerbi', (SELECT id FROM team WHERE name = 'Inter'), 3, 'D', 17, FALSE),
    ('Yann', 'Bisseck', (SELECT id FROM team WHERE name = 'Inter'), 4, 'D', 15, FALSE),
    ('Federico', 'Dimarco', (SELECT id FROM team WHERE name = 'Inter'), 5, 'D', 13, FALSE),
    ('Denzel', 'Dumfries', (SELECT id FROM team WHERE name = 'Inter'), 6, 'D', 11, FALSE),
    ('Matteo', 'Darmian', (SELECT id FROM team WHERE name = 'Inter'), 13, 'D', 9, FALSE),
    ('Carlos', 'Augusto', (SELECT id FROM team WHERE name = 'Inter'), 14, 'D', 7, TRUE),
    ('Benjamin', 'Pavard', (SELECT id FROM team WHERE name = 'Inter'), 15, 'D', 5, FALSE),
    ('Hakan', 'Calhanoglu', (SELECT id FROM team WHERE name = 'Inter'), 7, 'C', 50, FALSE),
    ('Nicolo', 'Barella', (SELECT id FROM team WHERE name = 'Inter'), 8, 'C', 43, FALSE),
    ('Henrikh', 'Mkhitaryan', (SELECT id FROM team WHERE name = 'Inter'), 10, 'C', 38, FALSE),
    ('Piotr', 'Zielinski', (SELECT id FROM team WHERE name = 'Inter'), 16, 'C', 33, FALSE),
    ('Davide', 'Frattesi', (SELECT id FROM team WHERE name = 'Inter'), 17, 'C', 28, FALSE),
    ('Kristjan', 'Asllani', (SELECT id FROM team WHERE name = 'Inter'), 18, 'C', 23, FALSE),
    ('Petar', 'Sucic', (SELECT id FROM team WHERE name = 'Inter'), 20, 'C', 18, FALSE),
    ('Andy', 'Diouf', (SELECT id FROM team WHERE name = 'Inter'), 21, 'C', 13, FALSE),
    ('Lautaro', 'Martinez', (SELECT id FROM team WHERE name = 'Inter'), 9, 'A', 60, FALSE),
    ('Marcus', 'Thuram', (SELECT id FROM team WHERE name = 'Inter'), 11, 'A', 48, FALSE),
    ('Mehdi', 'Taremi', (SELECT id FROM team WHERE name = 'Inter'), 19, 'A', 39, FALSE),
    ('Marko', 'Arnautovic', (SELECT id FROM team WHERE name = 'Inter'), 23, 'A', 30, FALSE),
    ('Pio', 'Esposito', (SELECT id FROM team WHERE name = 'Inter'), 24, 'A', 21, FALSE),
    ('Ange-Yoan', 'Bonny', (SELECT id FROM team WHERE name = 'Inter'), 25, 'A', 15, FALSE);

-- Juventus (strength 82, fascia forte) — 3 P / 8 D / 8 C / 6 A
INSERT INTO player (first_name, last_name, team_id, shirt_number, "position", price, injured) VALUES
    ('Michele', 'Di Gregorio', (SELECT id FROM team WHERE name = 'Juventus'), 1, 'P', 18, FALSE),
    ('Mattia', 'Perin', (SELECT id FROM team WHERE name = 'Juventus'), 12, 'P', 9, FALSE),
    ('Carlo', 'Pinsoglio', (SELECT id FROM team WHERE name = 'Juventus'), 22, 'P', 5, FALSE),
    ('Federico', 'Gatti', (SELECT id FROM team WHERE name = 'Juventus'), 2, 'D', 16, FALSE),
    ('Pierre', 'Kalulu', (SELECT id FROM team WHERE name = 'Juventus'), 3, 'D', 14, FALSE),
    ('Lloyd', 'Kelly', (SELECT id FROM team WHERE name = 'Juventus'), 4, 'D', 12, FALSE),
    ('Andrea', 'Cambiaso', (SELECT id FROM team WHERE name = 'Juventus'), 5, 'D', 10, FALSE),
    ('Juan', 'Cabal', (SELECT id FROM team WHERE name = 'Juventus'), 6, 'D', 9, FALSE),
    ('Daniele', 'Rugani', (SELECT id FROM team WHERE name = 'Juventus'), 13, 'D', 7, FALSE),
    ('Nicolo', 'Savona', (SELECT id FROM team WHERE name = 'Juventus'), 14, 'D', 6, TRUE),
    ('Renato', 'Veiga', (SELECT id FROM team WHERE name = 'Juventus'), 15, 'D', 4, FALSE),
    ('Kenan', 'Yildiz', (SELECT id FROM team WHERE name = 'Juventus'), 7, 'C', 42, FALSE),
    ('Manuel', 'Locatelli', (SELECT id FROM team WHERE name = 'Juventus'), 8, 'C', 36, FALSE),
    ('Khephren', 'Thuram', (SELECT id FROM team WHERE name = 'Juventus'), 10, 'C', 32, FALSE),
    ('Teun', 'Koopmeiners', (SELECT id FROM team WHERE name = 'Juventus'), 16, 'C', 27, FALSE),
    ('Weston', 'McKennie', (SELECT id FROM team WHERE name = 'Juventus'), 17, 'C', 23, FALSE),
    ('Fabio', 'Miretti', (SELECT id FROM team WHERE name = 'Juventus'), 18, 'C', 19, FALSE),
    ('Vasilije', 'Adzic', (SELECT id FROM team WHERE name = 'Juventus'), 20, 'C', 15, FALSE),
    ('Douglas', 'Luiz', (SELECT id FROM team WHERE name = 'Juventus'), 21, 'C', 11, FALSE),
    ('Dusan', 'Vlahovic', (SELECT id FROM team WHERE name = 'Juventus'), 9, 'A', 45, FALSE),
    ('Jonathan', 'David', (SELECT id FROM team WHERE name = 'Juventus'), 11, 'A', 36, FALSE),
    ('Nicolas', 'Gonzalez', (SELECT id FROM team WHERE name = 'Juventus'), 19, 'A', 29, FALSE),
    ('Francisco', 'Conceicao', (SELECT id FROM team WHERE name = 'Juventus'), 23, 'A', 23, FALSE),
    ('Timothy', 'Weah', (SELECT id FROM team WHERE name = 'Juventus'), 24, 'A', 16, FALSE),
    ('Lois', 'Openda', (SELECT id FROM team WHERE name = 'Juventus'), 25, 'A', 11, FALSE);

-- Milan (strength 80, fascia forte) — 3 P / 8 D / 8 C / 6 A
INSERT INTO player (first_name, last_name, team_id, shirt_number, "position", price, injured) VALUES
    ('Mike', 'Maignan', (SELECT id FROM team WHERE name = 'Milan'), 1, 'P', 18, FALSE),
    ('Marco', 'Sportiello', (SELECT id FROM team WHERE name = 'Milan'), 12, 'P', 9, FALSE),
    ('Lorenzo', 'Torriani', (SELECT id FROM team WHERE name = 'Milan'), 22, 'P', 5, FALSE),
    ('Fikayo', 'Tomori', (SELECT id FROM team WHERE name = 'Milan'), 2, 'D', 16, FALSE),
    ('Malick', 'Thiaw', (SELECT id FROM team WHERE name = 'Milan'), 3, 'D', 14, FALSE),
    ('Strahinja', 'Pavlovic', (SELECT id FROM team WHERE name = 'Milan'), 4, 'D', 12, FALSE),
    ('Davide', 'Bartesaghi', (SELECT id FROM team WHERE name = 'Milan'), 5, 'D', 10, FALSE),
    ('Alex', 'Jimenez', (SELECT id FROM team WHERE name = 'Milan'), 6, 'D', 9, FALSE),
    ('Odilon', 'Kossounou', (SELECT id FROM team WHERE name = 'Milan'), 13, 'D', 7, FALSE),
    ('Zachary', 'Athekame', (SELECT id FROM team WHERE name = 'Milan'), 14, 'D', 6, TRUE),
    ('Emerson', 'Royal', (SELECT id FROM team WHERE name = 'Milan'), 15, 'D', 4, FALSE),
    ('Luka', 'Modric', (SELECT id FROM team WHERE name = 'Milan'), 7, 'C', 42, FALSE),
    ('Youssouf', 'Fofana', (SELECT id FROM team WHERE name = 'Milan'), 8, 'C', 36, FALSE),
    ('Ismael', 'Bennacer', (SELECT id FROM team WHERE name = 'Milan'), 10, 'C', 32, FALSE),
    ('Adrien', 'Rabiot', (SELECT id FROM team WHERE name = 'Milan'), 16, 'C', 27, FALSE),
    ('Samuel', 'Chukwueze', (SELECT id FROM team WHERE name = 'Milan'), 17, 'C', 23, FALSE),
    ('Yunus', 'Musah', (SELECT id FROM team WHERE name = 'Milan'), 18, 'C', 19, FALSE),
    ('Warren', 'Bondo', (SELECT id FROM team WHERE name = 'Milan'), 20, 'C', 15, FALSE),
    ('Yacine', 'Adli', (SELECT id FROM team WHERE name = 'Milan'), 21, 'C', 11, FALSE),
    ('Rafael', 'Leao', (SELECT id FROM team WHERE name = 'Milan'), 9, 'A', 45, FALSE),
    ('Christian', 'Pulisic', (SELECT id FROM team WHERE name = 'Milan'), 11, 'A', 36, FALSE),
    ('Santiago', 'Gimenez', (SELECT id FROM team WHERE name = 'Milan'), 19, 'A', 29, FALSE),
    ('Christopher', 'Nkunku', (SELECT id FROM team WHERE name = 'Milan'), 23, 'A', 23, FALSE),
    ('Francesco', 'Camarda', (SELECT id FROM team WHERE name = 'Milan'), 24, 'A', 16, FALSE),
    ('Noah', 'Okafor', (SELECT id FROM team WHERE name = 'Milan'), 25, 'A', 11, FALSE);

-- Atalanta (strength 79, fascia forte) — 3 P / 8 D / 8 C / 6 A
INSERT INTO player (first_name, last_name, team_id, shirt_number, "position", price, injured) VALUES
    ('Marco', 'Carnesecchi', (SELECT id FROM team WHERE name = 'Atalanta'), 1, 'P', 18, FALSE),
    ('Rui', 'Patricio', (SELECT id FROM team WHERE name = 'Atalanta'), 12, 'P', 9, FALSE),
    ('Alessandro', 'Bertola', (SELECT id FROM team WHERE name = 'Atalanta'), 22, 'P', 5, FALSE),
    ('Berat', 'Djimsiti', (SELECT id FROM team WHERE name = 'Atalanta'), 2, 'D', 16, FALSE),
    ('Isak', 'Hien', (SELECT id FROM team WHERE name = 'Atalanta'), 3, 'D', 14, FALSE),
    ('Raoul', 'Bellanova', (SELECT id FROM team WHERE name = 'Atalanta'), 4, 'D', 12, FALSE),
    ('Matteo', 'Ruggeri', (SELECT id FROM team WHERE name = 'Atalanta'), 5, 'D', 10, FALSE),
    ('Davide', 'Zappacosta', (SELECT id FROM team WHERE name = 'Atalanta'), 6, 'D', 9, FALSE),
    ('Giorgio', 'Scalvini', (SELECT id FROM team WHERE name = 'Atalanta'), 13, 'D', 7, FALSE),
    ('Honest', 'Ahanor', (SELECT id FROM team WHERE name = 'Atalanta'), 14, 'D', 6, TRUE),
    ('Emil', 'Holm', (SELECT id FROM team WHERE name = 'Atalanta'), 15, 'D', 4, FALSE),
    ('Charles', 'De Ketelaere', (SELECT id FROM team WHERE name = 'Atalanta'), 7, 'C', 42, FALSE),
    ('Marten', 'de Roon', (SELECT id FROM team WHERE name = 'Atalanta'), 8, 'C', 36, FALSE),
    ('Ederson', 'Ederson', (SELECT id FROM team WHERE name = 'Atalanta'), 10, 'C', 32, FALSE),
    ('Mario', 'Pasalic', (SELECT id FROM team WHERE name = 'Atalanta'), 16, 'C', 27, FALSE),
    ('Marco', 'Brescianini', (SELECT id FROM team WHERE name = 'Atalanta'), 17, 'C', 23, FALSE),
    ('Lazar', 'Samardzic', (SELECT id FROM team WHERE name = 'Atalanta'), 18, 'C', 19, FALSE),
    ('Filip', 'Kostic', (SELECT id FROM team WHERE name = 'Atalanta'), 20, 'C', 15, FALSE),
    ('Kamaldeen', 'Sulemana', (SELECT id FROM team WHERE name = 'Atalanta'), 21, 'C', 11, FALSE),
    ('Ademola', 'Lookman', (SELECT id FROM team WHERE name = 'Atalanta'), 9, 'A', 45, FALSE),
    ('Mateo', 'Retegui', (SELECT id FROM team WHERE name = 'Atalanta'), 11, 'A', 36, FALSE),
    ('Nikola', 'Krstovic', (SELECT id FROM team WHERE name = 'Atalanta'), 19, 'A', 29, FALSE),
    ('Daniel', 'Maldini', (SELECT id FROM team WHERE name = 'Atalanta'), 23, 'A', 23, FALSE),
    ('El Bilal', 'Toure', (SELECT id FROM team WHERE name = 'Atalanta'), 24, 'A', 16, FALSE),
    ('Nicolo', 'Zaniolo', (SELECT id FROM team WHERE name = 'Atalanta'), 25, 'A', 11, FALSE);

-- Roma (strength 76, fascia forte) — 3 P / 8 D / 8 C / 6 A
INSERT INTO player (first_name, last_name, team_id, shirt_number, "position", price, injured) VALUES
    ('Mile', 'Svilar', (SELECT id FROM team WHERE name = 'Roma'), 1, 'P', 18, FALSE),
    ('Devis', 'Vasquez', (SELECT id FROM team WHERE name = 'Roma'), 12, 'P', 9, FALSE),
    ('Alessandro', 'Guidi', (SELECT id FROM team WHERE name = 'Roma'), 22, 'P', 5, FALSE),
    ('Gianluca', 'Mancini', (SELECT id FROM team WHERE name = 'Roma'), 2, 'D', 16, FALSE),
    ('Evan', 'Ndicka', (SELECT id FROM team WHERE name = 'Roma'), 3, 'D', 14, FALSE),
    ('Mario', 'Hermoso', (SELECT id FROM team WHERE name = 'Roma'), 4, 'D', 12, FALSE),
    ('Zeki', 'Celik', (SELECT id FROM team WHERE name = 'Roma'), 5, 'D', 10, FALSE),
    ('Devyne', 'Rensch', (SELECT id FROM team WHERE name = 'Roma'), 6, 'D', 9, FALSE),
    ('Wesley', 'Franca', (SELECT id FROM team WHERE name = 'Roma'), 13, 'D', 7, FALSE),
    ('Angelino', 'Angelino', (SELECT id FROM team WHERE name = 'Roma'), 14, 'D', 6, TRUE),
    ('Mikolaj', 'Ziolkowski', (SELECT id FROM team WHERE name = 'Roma'), 15, 'D', 4, FALSE),
    ('Lorenzo', 'Pellegrini', (SELECT id FROM team WHERE name = 'Roma'), 7, 'C', 42, FALSE),
    ('Manu', 'Kone', (SELECT id FROM team WHERE name = 'Roma'), 8, 'C', 36, FALSE),
    ('Bryan', 'Cristante', (SELECT id FROM team WHERE name = 'Roma'), 10, 'C', 32, FALSE),
    ('Tommaso', 'Baldanzi', (SELECT id FROM team WHERE name = 'Roma'), 16, 'C', 27, FALSE),
    ('Neil', 'El Aynaoui', (SELECT id FROM team WHERE name = 'Roma'), 17, 'C', 23, FALSE),
    ('Leandro', 'Paredes', (SELECT id FROM team WHERE name = 'Roma'), 18, 'C', 19, FALSE),
    ('Niccolo', 'Pisilli', (SELECT id FROM team WHERE name = 'Roma'), 20, 'C', 15, FALSE),
    ('Enzo', 'Le Fee', (SELECT id FROM team WHERE name = 'Roma'), 21, 'C', 11, FALSE),
    ('Artem', 'Dovbyk', (SELECT id FROM team WHERE name = 'Roma'), 9, 'A', 45, FALSE),
    ('Matias', 'Soule', (SELECT id FROM team WHERE name = 'Roma'), 11, 'A', 36, FALSE),
    ('Evan', 'Ferguson', (SELECT id FROM team WHERE name = 'Roma'), 19, 'A', 29, FALSE),
    ('Leon', 'Bailey', (SELECT id FROM team WHERE name = 'Roma'), 23, 'A', 23, FALSE),
    ('Eldor', 'Shomurodov', (SELECT id FROM team WHERE name = 'Roma'), 24, 'A', 16, FALSE),
    ('Stephan', 'El Shaarawy', (SELECT id FROM team WHERE name = 'Roma'), 25, 'A', 11, FALSE);

-- Bologna (strength 75, fascia forte) — 3 P / 8 D / 8 C / 6 A
INSERT INTO player (first_name, last_name, team_id, shirt_number, "position", price, injured) VALUES
    ('Lukasz', 'Skorupski', (SELECT id FROM team WHERE name = 'Bologna'), 1, 'P', 18, FALSE),
    ('Nicola', 'Bagnolini', (SELECT id FROM team WHERE name = 'Bologna'), 12, 'P', 9, FALSE),
    ('Federico', 'Ravaglia', (SELECT id FROM team WHERE name = 'Bologna'), 22, 'P', 5, FALSE),
    ('Jhon', 'Lucumi', (SELECT id FROM team WHERE name = 'Bologna'), 2, 'D', 16, FALSE),
    ('Stefan', 'Posch', (SELECT id FROM team WHERE name = 'Bologna'), 3, 'D', 14, FALSE),
    ('Martin', 'Erlic', (SELECT id FROM team WHERE name = 'Bologna'), 4, 'D', 12, FALSE),
    ('Nicolo', 'Casale', (SELECT id FROM team WHERE name = 'Bologna'), 5, 'D', 10, FALSE),
    ('Charalampos', 'Lykogiannis', (SELECT id FROM team WHERE name = 'Bologna'), 6, 'D', 9, FALSE),
    ('Marco', 'Pieragnolo', (SELECT id FROM team WHERE name = 'Bologna'), 13, 'D', 7, FALSE),
    ('Nicolo', 'Corazza', (SELECT id FROM team WHERE name = 'Bologna'), 14, 'D', 6, TRUE),
    ('Juan', 'Miranda', (SELECT id FROM team WHERE name = 'Bologna'), 15, 'D', 4, FALSE),
    ('Remo', 'Freuler', (SELECT id FROM team WHERE name = 'Bologna'), 7, 'C', 42, FALSE),
    ('Lewis', 'Ferguson', (SELECT id FROM team WHERE name = 'Bologna'), 8, 'C', 36, FALSE),
    ('Nikola', 'Moro', (SELECT id FROM team WHERE name = 'Bologna'), 10, 'C', 32, FALSE),
    ('Giovanni', 'Fabbian', (SELECT id FROM team WHERE name = 'Bologna'), 16, 'C', 27, FALSE),
    ('Tommaso', 'Pobega', (SELECT id FROM team WHERE name = 'Bologna'), 17, 'C', 23, FALSE),
    ('Michel', 'Aebischer', (SELECT id FROM team WHERE name = 'Bologna'), 18, 'C', 19, FALSE),
    ('Benjamin', 'Dominguez', (SELECT id FROM team WHERE name = 'Bologna'), 20, 'C', 15, FALSE),
    ('Kacper', 'Urbanski', (SELECT id FROM team WHERE name = 'Bologna'), 21, 'C', 11, FALSE),
    ('Ciro', 'Immobile', (SELECT id FROM team WHERE name = 'Bologna'), 9, 'A', 45, FALSE),
    ('Santiago', 'Castro', (SELECT id FROM team WHERE name = 'Bologna'), 11, 'A', 36, FALSE),
    ('Dan', 'Ndoye', (SELECT id FROM team WHERE name = 'Bologna'), 19, 'A', 29, FALSE),
    ('Riccardo', 'Orsolini', (SELECT id FROM team WHERE name = 'Bologna'), 23, 'A', 23, FALSE),
    ('Thijs', 'Dallinga', (SELECT id FROM team WHERE name = 'Bologna'), 24, 'A', 16, FALSE),
    ('Emil', 'Van Hooijdonk', (SELECT id FROM team WHERE name = 'Bologna'), 25, 'A', 11, FALSE);

-- Lazio (strength 74, fascia forte) — 3 P / 8 D / 8 C / 6 A
INSERT INTO player (first_name, last_name, team_id, shirt_number, "position", price, injured) VALUES
    ('Ivan', 'Provedel', (SELECT id FROM team WHERE name = 'Lazio'), 1, 'P', 18, FALSE),
    ('Christos', 'Mandas', (SELECT id FROM team WHERE name = 'Lazio'), 12, 'P', 9, FALSE),
    ('Alessio', 'Furlanetto', (SELECT id FROM team WHERE name = 'Lazio'), 22, 'P', 5, FALSE),
    ('Mario', 'Gila', (SELECT id FROM team WHERE name = 'Lazio'), 2, 'D', 16, FALSE),
    ('Adam', 'Marusic', (SELECT id FROM team WHERE name = 'Lazio'), 3, 'D', 14, FALSE),
    ('Nuno', 'Tavares', (SELECT id FROM team WHERE name = 'Lazio'), 4, 'D', 12, FALSE),
    ('Patric', 'Patric', (SELECT id FROM team WHERE name = 'Lazio'), 5, 'D', 10, FALSE),
    ('Oliver', 'Provstgaard', (SELECT id FROM team WHERE name = 'Lazio'), 6, 'D', 9, FALSE),
    ('Samuel', 'Gigot', (SELECT id FROM team WHERE name = 'Lazio'), 13, 'D', 7, FALSE),
    ('Manuel', 'Lazzari', (SELECT id FROM team WHERE name = 'Lazio'), 14, 'D', 6, TRUE),
    ('Alessandro', 'Sana', (SELECT id FROM team WHERE name = 'Lazio'), 15, 'D', 4, FALSE),
    ('Matteo', 'Guendouzi', (SELECT id FROM team WHERE name = 'Lazio'), 7, 'C', 42, FALSE),
    ('Nicolo', 'Rovella', (SELECT id FROM team WHERE name = 'Lazio'), 8, 'C', 36, FALSE),
    ('Danilo', 'Cataldi', (SELECT id FROM team WHERE name = 'Lazio'), 10, 'C', 32, FALSE),
    ('Fisayo', 'Dele-Bashiru', (SELECT id FROM team WHERE name = 'Lazio'), 16, 'C', 27, FALSE),
    ('Toma', 'Basic', (SELECT id FROM team WHERE name = 'Lazio'), 17, 'C', 23, FALSE),
    ('Matias', 'Vecino', (SELECT id FROM team WHERE name = 'Lazio'), 18, 'C', 19, FALSE),
    ('Reda', 'Belahyane', (SELECT id FROM team WHERE name = 'Lazio'), 20, 'C', 15, FALSE),
    ('Nicolo', 'Fresi', (SELECT id FROM team WHERE name = 'Lazio'), 21, 'C', 11, FALSE),
    ('Valentin', 'Castellanos', (SELECT id FROM team WHERE name = 'Lazio'), 9, 'A', 45, FALSE),
    ('Boulaye', 'Dia', (SELECT id FROM team WHERE name = 'Lazio'), 11, 'A', 36, FALSE),
    ('Pedro', 'Pedro', (SELECT id FROM team WHERE name = 'Lazio'), 19, 'A', 29, FALSE),
    ('Gustav', 'Isaksen', (SELECT id FROM team WHERE name = 'Lazio'), 23, 'A', 23, FALSE),
    ('Loum', 'Tchaouna', (SELECT id FROM team WHERE name = 'Lazio'), 24, 'A', 16, FALSE),
    ('Tijjani', 'Noslin', (SELECT id FROM team WHERE name = 'Lazio'), 25, 'A', 11, FALSE);

-- Fiorentina (strength 73, fascia forte) — 3 P / 8 D / 8 C / 6 A
INSERT INTO player (first_name, last_name, team_id, shirt_number, "position", price, injured) VALUES
    ('David', 'De Gea', (SELECT id FROM team WHERE name = 'Fiorentina'), 1, 'P', 18, FALSE),
    ('Tommaso', 'Martinelli', (SELECT id FROM team WHERE name = 'Fiorentina'), 12, 'P', 9, FALSE),
    ('Michele', 'Cerofolini', (SELECT id FROM team WHERE name = 'Fiorentina'), 22, 'P', 5, FALSE),
    ('Pietro', 'Comuzzo', (SELECT id FROM team WHERE name = 'Fiorentina'), 2, 'D', 16, FALSE),
    ('Marin', 'Pongracic', (SELECT id FROM team WHERE name = 'Fiorentina'), 3, 'D', 14, FALSE),
    ('Fabiano', 'Parisi', (SELECT id FROM team WHERE name = 'Fiorentina'), 4, 'D', 12, FALSE),
    ('Dodo', 'Dodo', (SELECT id FROM team WHERE name = 'Fiorentina'), 5, 'D', 10, FALSE),
    ('Luca', 'Ranieri', (SELECT id FROM team WHERE name = 'Fiorentina'), 6, 'D', 9, FALSE),
    ('Yerson', 'Mosquera', (SELECT id FROM team WHERE name = 'Fiorentina'), 13, 'D', 7, FALSE),
    ('Marco', 'Kayode', (SELECT id FROM team WHERE name = 'Fiorentina'), 14, 'D', 6, TRUE),
    ('Niccolo', 'Pierozzi', (SELECT id FROM team WHERE name = 'Fiorentina'), 15, 'D', 4, FALSE),
    ('Rolando', 'Mandragora', (SELECT id FROM team WHERE name = 'Fiorentina'), 7, 'C', 42, FALSE),
    ('Lorenzo', 'Amatucci', (SELECT id FROM team WHERE name = 'Fiorentina'), 8, 'C', 36, FALSE),
    ('Simon', 'Sohm', (SELECT id FROM team WHERE name = 'Fiorentina'), 10, 'C', 32, FALSE),
    ('Cher', 'Ndour', (SELECT id FROM team WHERE name = 'Fiorentina'), 16, 'C', 27, FALSE),
    ('Edoardo', 'Bove', (SELECT id FROM team WHERE name = 'Fiorentina'), 17, 'C', 23, FALSE),
    ('Riccardo', 'Sottil', (SELECT id FROM team WHERE name = 'Fiorentina'), 18, 'C', 19, FALSE),
    ('Jonathan', 'Ikone', (SELECT id FROM team WHERE name = 'Fiorentina'), 20, 'C', 15, FALSE),
    ('Fallou', 'Sene', (SELECT id FROM team WHERE name = 'Fiorentina'), 21, 'C', 11, FALSE),
    ('Moise', 'Kean', (SELECT id FROM team WHERE name = 'Fiorentina'), 9, 'A', 45, FALSE),
    ('Albert', 'Gudmundsson', (SELECT id FROM team WHERE name = 'Fiorentina'), 11, 'A', 36, FALSE),
    ('Roberto', 'Piccoli', (SELECT id FROM team WHERE name = 'Fiorentina'), 19, 'A', 29, FALSE),
    ('M''Bala', 'Nzola', (SELECT id FROM team WHERE name = 'Fiorentina'), 23, 'A', 23, FALSE),
    ('Christian', 'Kouame', (SELECT id FROM team WHERE name = 'Fiorentina'), 24, 'A', 16, FALSE),
    ('Lucas', 'Beltran', (SELECT id FROM team WHERE name = 'Fiorentina'), 25, 'A', 11, FALSE);

-- Como (strength 66, fascia media) — 3 P / 8 D / 8 C / 6 A
INSERT INTO player (first_name, last_name, team_id, shirt_number, "position", price, injured) VALUES
    ('Emil', 'Audero', (SELECT id FROM team WHERE name = 'Como'), 1, 'P', 12, FALSE),
    ('Jacopo', 'Furlan', (SELECT id FROM team WHERE name = 'Como'), 12, 'P', 6, FALSE),
    ('Marco', 'Peruzzi', (SELECT id FROM team WHERE name = 'Como'), 22, 'P', 3, FALSE),
    ('Marc-Oliver', 'Kempf', (SELECT id FROM team WHERE name = 'Como'), 2, 'D', 11, FALSE),
    ('Ivan', 'Smolcic', (SELECT id FROM team WHERE name = 'Como'), 3, 'D', 9, FALSE),
    ('Alberto', 'Dossena', (SELECT id FROM team WHERE name = 'Como'), 4, 'D', 8, FALSE),
    ('Yan', 'Diomande', (SELECT id FROM team WHERE name = 'Como'), 5, 'D', 7, FALSE),
    ('Alex', 'Valle', (SELECT id FROM team WHERE name = 'Como'), 6, 'D', 6, FALSE),
    ('Federico', 'Barba', (SELECT id FROM team WHERE name = 'Como'), 13, 'D', 5, FALSE),
    ('Edoardo', 'Goldaniga', (SELECT id FROM team WHERE name = 'Como'), 14, 'D', 4, TRUE),
    ('Alberto', 'Moreno', (SELECT id FROM team WHERE name = 'Como'), 15, 'D', 3, FALSE),
    ('Nico', 'Paz', (SELECT id FROM team WHERE name = 'Como'), 7, 'C', 25, FALSE),
    ('Maxence', 'Caqueret', (SELECT id FROM team WHERE name = 'Como'), 8, 'C', 21, FALSE),
    ('Martin', 'Baturina', (SELECT id FROM team WHERE name = 'Como'), 10, 'C', 19, FALSE),
    ('Gabriel', 'Strefezza', (SELECT id FROM team WHERE name = 'Como'), 16, 'C', 16, FALSE),
    ('Lucas', 'Da Cunha', (SELECT id FROM team WHERE name = 'Como'), 17, 'C', 14, FALSE),
    ('Ivan', 'Ilic', (SELECT id FROM team WHERE name = 'Como'), 18, 'C', 11, FALSE),
    ('Sergi', 'Roberto', (SELECT id FROM team WHERE name = 'Como'), 20, 'C', 9, FALSE),
    ('Marco', 'Sala', (SELECT id FROM team WHERE name = 'Como'), 21, 'C', 6, FALSE),
    ('Patrick', 'Cutrone', (SELECT id FROM team WHERE name = 'Como'), 9, 'A', 28, FALSE),
    ('Assane', 'Diao', (SELECT id FROM team WHERE name = 'Como'), 11, 'A', 22, FALSE),
    ('Andrea', 'Belotti', (SELECT id FROM team WHERE name = 'Como'), 19, 'A', 18, FALSE),
    ('Alieu', 'Fadera', (SELECT id FROM team WHERE name = 'Como'), 23, 'A', 14, FALSE),
    ('Jayden', 'Addai', (SELECT id FROM team WHERE name = 'Como'), 24, 'A', 10, FALSE),
    ('Alessandro', 'Gabrielloni', (SELECT id FROM team WHERE name = 'Como'), 25, 'A', 7, FALSE);

-- Torino (strength 62, fascia media) — 3 P / 8 D / 8 C / 6 A
INSERT INTO player (first_name, last_name, team_id, shirt_number, "position", price, injured) VALUES
    ('Vanja', 'Milinkovic-Savic', (SELECT id FROM team WHERE name = 'Torino'), 1, 'P', 12, FALSE),
    ('Franco', 'Israel', (SELECT id FROM team WHERE name = 'Torino'), 12, 'P', 6, FALSE),
    ('Luca', 'Gemello', (SELECT id FROM team WHERE name = 'Torino'), 22, 'P', 3, FALSE),
    ('Saul', 'Coco', (SELECT id FROM team WHERE name = 'Torino'), 2, 'D', 11, FALSE),
    ('Guillermo', 'Maripan', (SELECT id FROM team WHERE name = 'Torino'), 3, 'D', 9, FALSE),
    ('Adam', 'Masina', (SELECT id FROM team WHERE name = 'Torino'), 4, 'D', 8, FALSE),
    ('Marcus', 'Pedersen', (SELECT id FROM team WHERE name = 'Torino'), 5, 'D', 7, FALSE),
    ('Ottavio', 'Marenco', (SELECT id FROM team WHERE name = 'Torino'), 6, 'D', 6, FALSE),
    ('Kevin', 'Danilo', (SELECT id FROM team WHERE name = 'Torino'), 13, 'D', 5, FALSE),
    ('Nicolas', 'Schiavi', (SELECT id FROM team WHERE name = 'Torino'), 14, 'D', 4, TRUE),
    ('Ben', 'Kone', (SELECT id FROM team WHERE name = 'Torino'), 15, 'D', 3, FALSE),
    ('Samuele', 'Ricci', (SELECT id FROM team WHERE name = 'Torino'), 7, 'C', 25, FALSE),
    ('Cesare', 'Casadei', (SELECT id FROM team WHERE name = 'Torino'), 8, 'C', 21, FALSE),
    ('Nikola', 'Vlasic', (SELECT id FROM team WHERE name = 'Torino'), 10, 'C', 19, FALSE),
    ('Karol', 'Linetty', (SELECT id FROM team WHERE name = 'Torino'), 16, 'C', 16, FALSE),
    ('Adrien', 'Tameze', (SELECT id FROM team WHERE name = 'Torino'), 17, 'C', 14, FALSE),
    ('Emirhan', 'Ilkhan', (SELECT id FROM team WHERE name = 'Torino'), 18, 'C', 11, FALSE),
    ('Gvidas', 'Gineitis', (SELECT id FROM team WHERE name = 'Torino'), 20, 'C', 9, FALSE),
    ('Alieu', 'Njie', (SELECT id FROM team WHERE name = 'Torino'), 21, 'C', 6, FALSE),
    ('Duvan', 'Zapata', (SELECT id FROM team WHERE name = 'Torino'), 9, 'A', 28, FALSE),
    ('Antonio', 'Sanabria', (SELECT id FROM team WHERE name = 'Torino'), 11, 'A', 22, FALSE),
    ('Yann', 'Karamoh', (SELECT id FROM team WHERE name = 'Torino'), 19, 'A', 18, FALSE),
    ('Cyril', 'Ngonge', (SELECT id FROM team WHERE name = 'Torino'), 23, 'A', 14, FALSE),
    ('Che', 'Adams', (SELECT id FROM team WHERE name = 'Torino'), 24, 'A', 10, FALSE),
    ('Borja', 'Sainz', (SELECT id FROM team WHERE name = 'Torino'), 25, 'A', 7, FALSE);

-- Udinese (strength 60, fascia media) — 3 P / 8 D / 8 C / 6 A
INSERT INTO player (first_name, last_name, team_id, shirt_number, "position", price, injured) VALUES
    ('Razvan', 'Sava', (SELECT id FROM team WHERE name = 'Udinese'), 1, 'P', 12, FALSE),
    ('Maduka', 'Okoye', (SELECT id FROM team WHERE name = 'Udinese'), 12, 'P', 6, FALSE),
    ('Alessandro', 'Daffara', (SELECT id FROM team WHERE name = 'Udinese'), 22, 'P', 3, FALSE),
    ('Jaka', 'Bijol', (SELECT id FROM team WHERE name = 'Udinese'), 2, 'D', 11, FALSE),
    ('Christian', 'Kabasele', (SELECT id FROM team WHERE name = 'Udinese'), 3, 'D', 9, FALSE),
    ('Kingsley', 'Ehizibue', (SELECT id FROM team WHERE name = 'Udinese'), 4, 'D', 8, FALSE),
    ('Oumar', 'Solet', (SELECT id FROM team WHERE name = 'Udinese'), 5, 'D', 7, FALSE),
    ('Enzo', 'Ebosse', (SELECT id FROM team WHERE name = 'Udinese'), 6, 'D', 6, FALSE),
    ('Nicolas', 'Kamer', (SELECT id FROM team WHERE name = 'Udinese'), 13, 'D', 5, FALSE),
    ('Souleymane', 'Diakite', (SELECT id FROM team WHERE name = 'Udinese'), 14, 'D', 4, TRUE),
    ('Ivan', 'Nunez', (SELECT id FROM team WHERE name = 'Udinese'), 15, 'D', 3, FALSE),
    ('Sandi', 'Lovric', (SELECT id FROM team WHERE name = 'Udinese'), 7, 'C', 25, FALSE),
    ('Jurgen', 'Ekkelenkamp', (SELECT id FROM team WHERE name = 'Udinese'), 8, 'C', 21, FALSE),
    ('Simone', 'Pafundi', (SELECT id FROM team WHERE name = 'Udinese'), 10, 'C', 19, FALSE),
    ('Jesper', 'Karlsson', (SELECT id FROM team WHERE name = 'Udinese'), 16, 'C', 16, FALSE),
    ('Arthur', 'Atta', (SELECT id FROM team WHERE name = 'Udinese'), 17, 'C', 14, FALSE),
    ('Oier', 'Zarraga', (SELECT id FROM team WHERE name = 'Udinese'), 18, 'C', 11, FALSE),
    ('Thomas', 'Kristensen', (SELECT id FROM team WHERE name = 'Udinese'), 20, 'C', 9, FALSE),
    ('Florian', 'Thauvin', (SELECT id FROM team WHERE name = 'Udinese'), 21, 'C', 6, FALSE),
    ('Iker', 'Bravo', (SELECT id FROM team WHERE name = 'Udinese'), 9, 'A', 28, FALSE),
    ('Keinan', 'Davis', (SELECT id FROM team WHERE name = 'Udinese'), 11, 'A', 22, FALSE),
    ('Elia', 'Petrelli', (SELECT id FROM team WHERE name = 'Udinese'), 19, 'A', 18, FALSE),
    ('Joel', 'Ranilla', (SELECT id FROM team WHERE name = 'Udinese'), 23, 'A', 14, FALSE),
    ('Festy', 'Ebosele', (SELECT id FROM team WHERE name = 'Udinese'), 24, 'A', 10, FALSE),
    ('Roberto', 'Pereyra', (SELECT id FROM team WHERE name = 'Udinese'), 25, 'A', 7, FALSE);

-- Genoa (strength 58, fascia media) — 3 P / 8 D / 8 C / 6 A
INSERT INTO player (first_name, last_name, team_id, shirt_number, "position", price, injured) VALUES
    ('Nicola', 'Leali', (SELECT id FROM team WHERE name = 'Genoa'), 1, 'P', 12, FALSE),
    ('Pierluigi', 'Gollini', (SELECT id FROM team WHERE name = 'Genoa'), 12, 'P', 6, FALSE),
    ('Sebastiano', 'Desplanches', (SELECT id FROM team WHERE name = 'Genoa'), 22, 'P', 3, FALSE),
    ('Aaron', 'Martin', (SELECT id FROM team WHERE name = 'Genoa'), 2, 'D', 11, FALSE),
    ('Johan', 'Vasquez', (SELECT id FROM team WHERE name = 'Genoa'), 3, 'D', 9, FALSE),
    ('Koni', 'De Winter', (SELECT id FROM team WHERE name = 'Genoa'), 4, 'D', 8, FALSE),
    ('Alan', 'Matturro', (SELECT id FROM team WHERE name = 'Genoa'), 5, 'D', 7, FALSE),
    ('Alessandro', 'Marcandalli', (SELECT id FROM team WHERE name = 'Genoa'), 6, 'D', 6, FALSE),
    ('Mario', 'Sadick', (SELECT id FROM team WHERE name = 'Genoa'), 13, 'D', 5, FALSE),
    ('Jayden', 'Sant', (SELECT id FROM team WHERE name = 'Genoa'), 14, 'D', 4, TRUE),
    ('Milan', 'Cabinski', (SELECT id FROM team WHERE name = 'Genoa'), 15, 'D', 3, FALSE),
    ('Morten', 'Frendrup', (SELECT id FROM team WHERE name = 'Genoa'), 7, 'C', 25, FALSE),
    ('Milan', 'Badelj', (SELECT id FROM team WHERE name = 'Genoa'), 8, 'C', 21, FALSE),
    ('Ruslan', 'Malinovskyi', (SELECT id FROM team WHERE name = 'Genoa'), 10, 'C', 19, FALSE),
    ('Valentin', 'Carboni', (SELECT id FROM team WHERE name = 'Genoa'), 16, 'C', 16, FALSE),
    ('Silvano', 'Vranckx', (SELECT id FROM team WHERE name = 'Genoa'), 17, 'C', 14, FALSE),
    ('Patrizio', 'Masini', (SELECT id FROM team WHERE name = 'Genoa'), 18, 'C', 11, FALSE),
    ('Stefano', 'Sabelli', (SELECT id FROM team WHERE name = 'Genoa'), 20, 'C', 9, FALSE),
    ('Brooke', 'Norton-Cuffy', (SELECT id FROM team WHERE name = 'Genoa'), 21, 'C', 6, FALSE),
    ('Vitinha', 'Vitinha', (SELECT id FROM team WHERE name = 'Genoa'), 9, 'A', 28, FALSE),
    ('Caleb', 'Ekuban', (SELECT id FROM team WHERE name = 'Genoa'), 11, 'A', 22, FALSE),
    ('Junior', 'Messias', (SELECT id FROM team WHERE name = 'Genoa'), 19, 'A', 18, FALSE),
    ('Andrea', 'Pinamonti', (SELECT id FROM team WHERE name = 'Genoa'), 23, 'A', 14, FALSE),
    ('Hugo', 'Cuenca', (SELECT id FROM team WHERE name = 'Genoa'), 24, 'A', 10, FALSE),
    ('Milan', 'Djuric', (SELECT id FROM team WHERE name = 'Genoa'), 25, 'A', 7, FALSE);

-- Cagliari (strength 56, fascia media) — 3 P / 8 D / 8 C / 6 A
INSERT INTO player (first_name, last_name, team_id, shirt_number, "position", price, injured) VALUES
    ('Simone', 'Scuffet', (SELECT id FROM team WHERE name = 'Cagliari'), 1, 'P', 12, FALSE),
    ('Alberto', 'Boccolini', (SELECT id FROM team WHERE name = 'Cagliari'), 12, 'P', 6, FALSE),
    ('Pietro', 'Ciocci', (SELECT id FROM team WHERE name = 'Cagliari'), 22, 'P', 3, FALSE),
    ('Yerry', 'Mina', (SELECT id FROM team WHERE name = 'Cagliari'), 2, 'D', 11, FALSE),
    ('Adam', 'Obert', (SELECT id FROM team WHERE name = 'Cagliari'), 3, 'D', 9, FALSE),
    ('Gabriele', 'Zappa', (SELECT id FROM team WHERE name = 'Cagliari'), 4, 'D', 8, FALSE),
    ('Sebastiano', 'Luperto', (SELECT id FROM team WHERE name = 'Cagliari'), 5, 'D', 7, FALSE),
    ('Marco', 'Palestra', (SELECT id FROM team WHERE name = 'Cagliari'), 6, 'D', 6, FALSE),
    ('Mateusz', 'Wieteska', (SELECT id FROM team WHERE name = 'Cagliari'), 13, 'D', 5, FALSE),
    ('Antonio', 'Mazzotta', (SELECT id FROM team WHERE name = 'Cagliari'), 14, 'D', 4, TRUE),
    ('Michael', 'Kayode', (SELECT id FROM team WHERE name = 'Cagliari'), 15, 'D', 3, FALSE),
    ('Nadir', 'Zortea', (SELECT id FROM team WHERE name = 'Cagliari'), 7, 'C', 25, FALSE),
    ('Alessandro', 'Deiola', (SELECT id FROM team WHERE name = 'Cagliari'), 8, 'C', 21, FALSE),
    ('Antoine', 'Makoumbou', (SELECT id FROM team WHERE name = 'Cagliari'), 10, 'C', 19, FALSE),
    ('Nicolas', 'Viola', (SELECT id FROM team WHERE name = 'Cagliari'), 16, 'C', 16, FALSE),
    ('Marco', 'Mancosu', (SELECT id FROM team WHERE name = 'Cagliari'), 17, 'C', 14, FALSE),
    ('Jakub', 'Jankto', (SELECT id FROM team WHERE name = 'Cagliari'), 18, 'C', 11, FALSE),
    ('Andrea', 'Ciocci', (SELECT id FROM team WHERE name = 'Cagliari'), 20, 'C', 9, FALSE),
    ('Riccardo', 'Marchizza', (SELECT id FROM team WHERE name = 'Cagliari'), 21, 'C', 6, FALSE),
    ('Gianluca', 'Lapadula', (SELECT id FROM team WHERE name = 'Cagliari'), 9, 'A', 28, FALSE),
    ('Zito', 'Luvumbo', (SELECT id FROM team WHERE name = 'Cagliari'), 11, 'A', 22, FALSE),
    ('Roberto', 'Piccoli', (SELECT id FROM team WHERE name = 'Cagliari'), 19, 'A', 18, FALSE),
    ('Andrea', 'Belotti', (SELECT id FROM team WHERE name = 'Cagliari'), 23, 'A', 14, FALSE),
    ('Sebastiano', 'Esposito', (SELECT id FROM team WHERE name = 'Cagliari'), 24, 'A', 10, FALSE),
    ('Leonardo', 'Pavoletti', (SELECT id FROM team WHERE name = 'Cagliari'), 25, 'A', 7, FALSE);

-- Hellas Verona (strength 54, fascia media) — 3 P / 8 D / 8 C / 6 A
INSERT INTO player (first_name, last_name, team_id, shirt_number, "position", price, injured) VALUES
    ('Lorenzo', 'Montipo', (SELECT id FROM team WHERE name = 'Hellas Verona'), 1, 'P', 12, FALSE),
    ('Simone', 'Perisan', (SELECT id FROM team WHERE name = 'Hellas Verona'), 12, 'P', 6, FALSE),
    ('Michael', 'Agazzi', (SELECT id FROM team WHERE name = 'Hellas Verona'), 22, 'P', 3, FALSE),
    ('Diego', 'Coppola', (SELECT id FROM team WHERE name = 'Hellas Verona'), 2, 'D', 11, FALSE),
    ('Martin', 'Frese', (SELECT id FROM team WHERE name = 'Hellas Verona'), 3, 'D', 9, FALSE),
    ('Fabio', 'Gunter', (SELECT id FROM team WHERE name = 'Hellas Verona'), 4, 'D', 8, FALSE),
    ('Daniele', 'Ghilardi', (SELECT id FROM team WHERE name = 'Hellas Verona'), 5, 'D', 7, FALSE),
    ('Giovanni', 'Corradini', (SELECT id FROM team WHERE name = 'Hellas Verona'), 6, 'D', 6, FALSE),
    ('Pawel', 'Dawidowicz', (SELECT id FROM team WHERE name = 'Hellas Verona'), 13, 'D', 5, FALSE),
    ('Josh', 'Doig', (SELECT id FROM team WHERE name = 'Hellas Verona'), 14, 'D', 4, TRUE),
    ('Malick', 'Yalcouye', (SELECT id FROM team WHERE name = 'Hellas Verona'), 15, 'D', 3, FALSE),
    ('Tomas', 'Suslov', (SELECT id FROM team WHERE name = 'Hellas Verona'), 7, 'C', 25, FALSE),
    ('Ondrej', 'Duda', (SELECT id FROM team WHERE name = 'Hellas Verona'), 8, 'C', 21, FALSE),
    ('Darko', 'Lazovic', (SELECT id FROM team WHERE name = 'Hellas Verona'), 10, 'C', 19, FALSE),
    ('Suat', 'Serdar', (SELECT id FROM team WHERE name = 'Hellas Verona'), 16, 'C', 16, FALSE),
    ('Xavier', 'Nzosa', (SELECT id FROM team WHERE name = 'Hellas Verona'), 17, 'C', 14, FALSE),
    ('Emmanuel', 'Gyasi', (SELECT id FROM team WHERE name = 'Hellas Verona'), 18, 'C', 11, FALSE),
    ('Grigoris', 'Kastanos', (SELECT id FROM team WHERE name = 'Hellas Verona'), 20, 'C', 9, FALSE),
    ('Filip', 'Stankovic', (SELECT id FROM team WHERE name = 'Hellas Verona'), 21, 'C', 6, FALSE),
    ('Casper', 'Tengstedt', (SELECT id FROM team WHERE name = 'Hellas Verona'), 9, 'A', 28, FALSE),
    ('Frank', 'Tsadjout', (SELECT id FROM team WHERE name = 'Hellas Verona'), 11, 'A', 22, FALSE),
    ('Kevin', 'Vandenbergh', (SELECT id FROM team WHERE name = 'Hellas Verona'), 19, 'A', 18, FALSE),
    ('Amin', 'Sarr', (SELECT id FROM team WHERE name = 'Hellas Verona'), 23, 'A', 14, FALSE),
    ('Ajdin', 'Zeljkovic', (SELECT id FROM team WHERE name = 'Hellas Verona'), 24, 'A', 10, FALSE),
    ('Giovane', 'Giovane', (SELECT id FROM team WHERE name = 'Hellas Verona'), 25, 'A', 7, FALSE);

-- Lecce (strength 52, fascia bassa) — 3 P / 8 D / 8 C / 6 A
INSERT INTO player (first_name, last_name, team_id, shirt_number, "position", price, injured) VALUES
    ('Wladimiro', 'Falcone', (SELECT id FROM team WHERE name = 'Lecce'), 1, 'P', 9, FALSE),
    ('Nicolas', 'Jean', (SELECT id FROM team WHERE name = 'Lecce'), 12, 'P', 5, FALSE),
    ('Alex', 'Bleve', (SELECT id FROM team WHERE name = 'Lecce'), 22, 'P', 2, FALSE),
    ('Antonino', 'Gallo', (SELECT id FROM team WHERE name = 'Lecce'), 2, 'D', 8, FALSE),
    ('Federico', 'Baschirotto', (SELECT id FROM team WHERE name = 'Lecce'), 3, 'D', 7, FALSE),
    ('Kialonda', 'Gaspar', (SELECT id FROM team WHERE name = 'Lecce'), 4, 'D', 6, FALSE),
    ('Marcos', 'Curado', (SELECT id FROM team WHERE name = 'Lecce'), 5, 'D', 5, FALSE),
    ('Lorenzo', 'Venuti', (SELECT id FROM team WHERE name = 'Lecce'), 6, 'D', 4, FALSE),
    ('Balthazar', 'Pierret', (SELECT id FROM team WHERE name = 'Lecce'), 13, 'D', 4, FALSE),
    ('Jean Freddi', 'Greco', (SELECT id FROM team WHERE name = 'Lecce'), 14, 'D', 3, TRUE),
    ('Alessandro', 'Rizzo', (SELECT id FROM team WHERE name = 'Lecce'), 15, 'D', 2, FALSE),
    ('Ylber', 'Ramadani', (SELECT id FROM team WHERE name = 'Lecce'), 7, 'C', 16, FALSE),
    ('Hamza', 'Rafia', (SELECT id FROM team WHERE name = 'Lecce'), 8, 'C', 14, FALSE),
    ('Medon', 'Berisha', (SELECT id FROM team WHERE name = 'Lecce'), 10, 'C', 12, FALSE),
    ('Lassana', 'Coulibaly', (SELECT id FROM team WHERE name = 'Lecce'), 16, 'C', 10, FALSE),
    ('Santiago', 'Pierotti', (SELECT id FROM team WHERE name = 'Lecce'), 17, 'C', 9, FALSE),
    ('Andrea', 'Helgason', (SELECT id FROM team WHERE name = 'Lecce'), 18, 'C', 7, FALSE),
    ('Nikola', 'Ndaba', (SELECT id FROM team WHERE name = 'Lecce'), 20, 'C', 6, FALSE),
    ('Zied', 'El Ouahdi', (SELECT id FROM team WHERE name = 'Lecce'), 21, 'C', 4, FALSE),
    ('Lameck', 'Banda', (SELECT id FROM team WHERE name = 'Lecce'), 9, 'A', 18, FALSE),
    ('Ante', 'Rebic', (SELECT id FROM team WHERE name = 'Lecce'), 11, 'A', 14, FALSE),
    ('Pontus', 'Almqvist', (SELECT id FROM team WHERE name = 'Lecce'), 19, 'A', 12, FALSE),
    ('Nikola', 'Stulic', (SELECT id FROM team WHERE name = 'Lecce'), 23, 'A', 9, FALSE),
    ('Idrissa', 'Toure', (SELECT id FROM team WHERE name = 'Lecce'), 24, 'A', 6, FALSE),
    ('Tete', 'Morente', (SELECT id FROM team WHERE name = 'Lecce'), 25, 'A', 5, FALSE);

-- Parma (strength 51, fascia bassa) — 3 P / 8 D / 8 C / 6 A
INSERT INTO player (first_name, last_name, team_id, shirt_number, "position", price, injured) VALUES
    ('Zion', 'Suzuki', (SELECT id FROM team WHERE name = 'Parma'), 1, 'P', 9, FALSE),
    ('Corrado', 'Colombo', (SELECT id FROM team WHERE name = 'Parma'), 12, 'P', 5, FALSE),
    ('Filippo', 'Corvi', (SELECT id FROM team WHERE name = 'Parma'), 22, 'P', 2, FALSE),
    ('Botond', 'Balogh', (SELECT id FROM team WHERE name = 'Parma'), 2, 'D', 8, FALSE),
    ('Woyo', 'Coulibaly', (SELECT id FROM team WHERE name = 'Parma'), 3, 'D', 7, FALSE),
    ('Enrico', 'Delprato', (SELECT id FROM team WHERE name = 'Parma'), 4, 'D', 6, FALSE),
    ('Anthony', 'Hainaut', (SELECT id FROM team WHERE name = 'Parma'), 5, 'D', 5, FALSE),
    ('Christian', 'Ordonez', (SELECT id FROM team WHERE name = 'Parma'), 6, 'D', 4, FALSE),
    ('Alessandro', 'Circati', (SELECT id FROM team WHERE name = 'Parma'), 13, 'D', 4, FALSE),
    ('Giuseppe', 'Suzzi', (SELECT id FROM team WHERE name = 'Parma'), 14, 'D', 3, TRUE),
    ('Yordan', 'Osorio', (SELECT id FROM team WHERE name = 'Parma'), 15, 'D', 2, FALSE),
    ('Adrian', 'Bernabe', (SELECT id FROM team WHERE name = 'Parma'), 7, 'C', 16, FALSE),
    ('Emanuel', 'Vignato', (SELECT id FROM team WHERE name = 'Parma'), 8, 'C', 14, FALSE),
    ('Hernani', 'Hernani', (SELECT id FROM team WHERE name = 'Parma'), 10, 'C', 12, FALSE),
    ('Mandela', 'Keita', (SELECT id FROM team WHERE name = 'Parma'), 16, 'C', 10, FALSE),
    ('Nahuel', 'Estevez', (SELECT id FROM team WHERE name = 'Parma'), 17, 'C', 9, FALSE),
    ('Anthony', 'Partipilo', (SELECT id FROM team WHERE name = 'Parma'), 18, 'C', 7, FALSE),
    ('Enrico', 'Baldini', (SELECT id FROM team WHERE name = 'Parma'), 20, 'C', 6, FALSE),
    ('Federico', 'Bonny', (SELECT id FROM team WHERE name = 'Parma'), 21, 'C', 4, FALSE),
    ('Dennis', 'Man', (SELECT id FROM team WHERE name = 'Parma'), 9, 'A', 18, FALSE),
    ('Adrian', 'Benedyczak', (SELECT id FROM team WHERE name = 'Parma'), 11, 'A', 14, FALSE),
    ('Valentin', 'Mihaila', (SELECT id FROM team WHERE name = 'Parma'), 19, 'A', 12, FALSE),
    ('Alassane', 'Ndour', (SELECT id FROM team WHERE name = 'Parma'), 23, 'A', 9, FALSE),
    ('Kevin', 'Lasagna', (SELECT id FROM team WHERE name = 'Parma'), 24, 'A', 6, FALSE),
    ('Patrick', 'Ekwah', (SELECT id FROM team WHERE name = 'Parma'), 25, 'A', 5, FALSE);

-- Sassuolo (strength 50, fascia bassa) — 3 P / 8 D / 8 C / 6 A
INSERT INTO player (first_name, last_name, team_id, shirt_number, "position", price, injured) VALUES
    ('Stefano', 'Turati', (SELECT id FROM team WHERE name = 'Sassuolo'), 1, 'P', 9, FALSE),
    ('Andrea', 'Consigli', (SELECT id FROM team WHERE name = 'Sassuolo'), 12, 'P', 5, FALSE),
    ('Alessio', 'Russo', (SELECT id FROM team WHERE name = 'Sassuolo'), 22, 'P', 2, FALSE),
    ('Filippo', 'Romagna', (SELECT id FROM team WHERE name = 'Sassuolo'), 2, 'D', 8, FALSE),
    ('Antonio', 'Candela', (SELECT id FROM team WHERE name = 'Sassuolo'), 3, 'D', 7, FALSE),
    ('Filippo', 'Missori', (SELECT id FROM team WHERE name = 'Sassuolo'), 4, 'D', 6, FALSE),
    ('Luca', 'Vignali', (SELECT id FROM team WHERE name = 'Sassuolo'), 5, 'D', 5, FALSE),
    ('Marcus', 'Pierre', (SELECT id FROM team WHERE name = 'Sassuolo'), 6, 'D', 4, FALSE),
    ('Nicholas', 'Pierini', (SELECT id FROM team WHERE name = 'Sassuolo'), 13, 'D', 4, FALSE),
    ('Vasileios', 'Lampropoulos', (SELECT id FROM team WHERE name = 'Sassuolo'), 14, 'D', 3, TRUE),
    ('Rocco', 'Ghilardi', (SELECT id FROM team WHERE name = 'Sassuolo'), 15, 'D', 2, FALSE),
    ('Cristian', 'Volpato', (SELECT id FROM team WHERE name = 'Sassuolo'), 7, 'C', 16, FALSE),
    ('Pedro', 'Obiang', (SELECT id FROM team WHERE name = 'Sassuolo'), 8, 'C', 14, FALSE),
    ('Ismael', 'Kone', (SELECT id FROM team WHERE name = 'Sassuolo'), 10, 'C', 12, FALSE),
    ('Daniel', 'Boloca', (SELECT id FROM team WHERE name = 'Sassuolo'), 16, 'C', 10, FALSE),
    ('Cristian', 'Buchel', (SELECT id FROM team WHERE name = 'Sassuolo'), 17, 'C', 9, FALSE),
    ('Manuel', 'Ricci', (SELECT id FROM team WHERE name = 'Sassuolo'), 18, 'C', 7, FALSE),
    ('Samuele', 'Angori', (SELECT id FROM team WHERE name = 'Sassuolo'), 20, 'C', 6, FALSE),
    ('Flavius', 'Daniliuc', (SELECT id FROM team WHERE name = 'Sassuolo'), 21, 'C', 4, FALSE),
    ('Domenico', 'Berardi', (SELECT id FROM team WHERE name = 'Sassuolo'), 9, 'A', 18, FALSE),
    ('Armand', 'Lauriente', (SELECT id FROM team WHERE name = 'Sassuolo'), 11, 'A', 14, FALSE),
    ('Emil', 'Konradsen Ceide', (SELECT id FROM team WHERE name = 'Sassuolo'), 19, 'A', 12, FALSE),
    ('Gennaro', 'Tutino', (SELECT id FROM team WHERE name = 'Sassuolo'), 23, 'A', 9, FALSE),
    ('Cristian', 'Shpendi', (SELECT id FROM team WHERE name = 'Sassuolo'), 24, 'A', 6, FALSE),
    ('Alberto', 'Cerri', (SELECT id FROM team WHERE name = 'Sassuolo'), 25, 'A', 5, FALSE);

-- Pisa (strength 46, fascia bassa) — 3 P / 8 D / 8 C / 6 A
INSERT INTO player (first_name, last_name, team_id, shirt_number, "position", price, injured) VALUES
    ('Adrian', 'Semper', (SELECT id FROM team WHERE name = 'Pisa'), 1, 'P', 9, FALSE),
    ('Marco', 'Loria', (SELECT id FROM team WHERE name = 'Pisa'), 12, 'P', 5, FALSE),
    ('Nicholas', 'Sorrentino', (SELECT id FROM team WHERE name = 'Pisa'), 22, 'P', 2, FALSE),
    ('Simone', 'Canestrelli', (SELECT id FROM team WHERE name = 'Pisa'), 2, 'D', 8, FALSE),
    ('Antonio', 'Caracciolo', (SELECT id FROM team WHERE name = 'Pisa'), 3, 'D', 7, FALSE),
    ('Alessandro', 'Rus', (SELECT id FROM team WHERE name = 'Pisa'), 4, 'D', 6, FALSE),
    ('Giovanni', 'Bonfanti', (SELECT id FROM team WHERE name = 'Pisa'), 5, 'D', 5, FALSE),
    ('Lorenzo', 'Tosi', (SELECT id FROM team WHERE name = 'Pisa'), 6, 'D', 4, FALSE),
    ('Christian', 'Piccinini', (SELECT id FROM team WHERE name = 'Pisa'), 13, 'D', 4, FALSE),
    ('Salvatore', 'Elia', (SELECT id FROM team WHERE name = 'Pisa'), 14, 'D', 3, TRUE),
    ('Marco', 'Angori', (SELECT id FROM team WHERE name = 'Pisa'), 15, 'D', 2, FALSE),
    ('Marius', 'Marin', (SELECT id FROM team WHERE name = 'Pisa'), 7, 'C', 16, FALSE),
    ('Vincenzo', 'D''Amico', (SELECT id FROM team WHERE name = 'Pisa'), 8, 'C', 14, FALSE),
    ('Alessio', 'Tramoni', (SELECT id FROM team WHERE name = 'Pisa'), 10, 'C', 12, FALSE),
    ('Antonio', 'Barba', (SELECT id FROM team WHERE name = 'Pisa'), 16, 'C', 10, FALSE),
    ('Michele', 'Marconi', (SELECT id FROM team WHERE name = 'Pisa'), 17, 'C', 9, FALSE),
    ('Valerio', 'Mazzitelli', (SELECT id FROM team WHERE name = 'Pisa'), 18, 'C', 7, FALSE),
    ('Leonardo', 'Morutan', (SELECT id FROM team WHERE name = 'Pisa'), 20, 'C', 6, FALSE),
    ('Simone', 'Ganz', (SELECT id FROM team WHERE name = 'Pisa'), 21, 'C', 4, FALSE),
    ('Nicolas', 'Bonfanti', (SELECT id FROM team WHERE name = 'Pisa'), 9, 'A', 18, FALSE),
    ('Matteo', 'Tramoni', (SELECT id FROM team WHERE name = 'Pisa'), 11, 'A', 14, FALSE),
    ('Raphael', 'Odogwu', (SELECT id FROM team WHERE name = 'Pisa'), 19, 'A', 12, FALSE),
    ('Silvio', 'Israel', (SELECT id FROM team WHERE name = 'Pisa'), 23, 'A', 9, FALSE),
    ('Gabriele', 'Moncini', (SELECT id FROM team WHERE name = 'Pisa'), 24, 'A', 6, FALSE),
    ('Ionut', 'Nicolae', (SELECT id FROM team WHERE name = 'Pisa'), 25, 'A', 5, FALSE);

-- Cremonese (strength 45, fascia bassa) — 3 P / 8 D / 8 C / 6 A
INSERT INTO player (first_name, last_name, team_id, shirt_number, "position", price, injured) VALUES
    ('Michael', 'Fulignati', (SELECT id FROM team WHERE name = 'Cremonese'), 1, 'P', 9, FALSE),
    ('Elia', 'Nardi', (SELECT id FROM team WHERE name = 'Cremonese'), 12, 'P', 5, FALSE),
    ('Marco', 'Furlan', (SELECT id FROM team WHERE name = 'Cremonese'), 22, 'P', 2, FALSE),
    ('Michele', 'Bianchetti', (SELECT id FROM team WHERE name = 'Cremonese'), 2, 'D', 8, FALSE),
    ('Riccardo', 'Ravanelli', (SELECT id FROM team WHERE name = 'Cremonese'), 3, 'D', 7, FALSE),
    ('Simone', 'Lochoshvili', (SELECT id FROM team WHERE name = 'Cremonese'), 4, 'D', 6, FALSE),
    ('Federico', 'Ceccherini', (SELECT id FROM team WHERE name = 'Cremonese'), 5, 'D', 5, FALSE),
    ('Emanuele', 'Valeri', (SELECT id FROM team WHERE name = 'Cremonese'), 6, 'D', 4, FALSE),
    ('Pietro', 'Fiordaliso', (SELECT id FROM team WHERE name = 'Cremonese'), 13, 'D', 4, FALSE),
    ('Leonardo', 'Sernicola', (SELECT id FROM team WHERE name = 'Cremonese'), 14, 'D', 3, TRUE),
    ('Simone', 'Ghisolfi', (SELECT id FROM team WHERE name = 'Cremonese'), 15, 'D', 2, FALSE),
    ('Cristian', 'Buonaiuto', (SELECT id FROM team WHERE name = 'Cremonese'), 7, 'C', 16, FALSE),
    ('Charles', 'Pickel', (SELECT id FROM team WHERE name = 'Cremonese'), 8, 'C', 14, FALSE),
    ('Filippo', 'Bianco', (SELECT id FROM team WHERE name = 'Cremonese'), 10, 'C', 12, FALSE),
    ('Fares', 'Chaibi', (SELECT id FROM team WHERE name = 'Cremonese'), 16, 'C', 10, FALSE),
    ('Michele', 'Collocolo', (SELECT id FROM team WHERE name = 'Cremonese'), 17, 'C', 9, FALSE),
    ('Luca', 'Zanimacchia', (SELECT id FROM team WHERE name = 'Cremonese'), 18, 'C', 7, FALSE),
    ('Alessandro', 'Vogliacco', (SELECT id FROM team WHERE name = 'Cremonese'), 20, 'C', 6, FALSE),
    ('Nicola', 'Castagnetti', (SELECT id FROM team WHERE name = 'Cremonese'), 21, 'C', 4, FALSE),
    ('David', 'Okereke', (SELECT id FROM team WHERE name = 'Cremonese'), 9, 'A', 18, FALSE),
    ('Franco', 'Vazquez', (SELECT id FROM team WHERE name = 'Cremonese'), 11, 'A', 14, FALSE),
    ('Matteo', 'Bortolussi', (SELECT id FROM team WHERE name = 'Cremonese'), 19, 'A', 12, FALSE),
    ('Antonino', 'Ragusa', (SELECT id FROM team WHERE name = 'Cremonese'), 23, 'A', 9, FALSE),
    ('Kelvin', 'Amoah', (SELECT id FROM team WHERE name = 'Cremonese'), 24, 'A', 6, FALSE),
    ('Alessio', 'Zerbin', (SELECT id FROM team WHERE name = 'Cremonese'), 25, 'A', 5, FALSE);
